#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# 设置 Node 环境
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

# 添加 node_modules/.bin 到环境变量
export PATH="$PATH:./node_modules/.bin"

# 执行 lint-staged
pnpm lint-staged